[package]
name = "ray"
version = "0.1.0"
authors = ["Mikhail Pak <code@mp4096.com>"]
edition = "2018"

[dependencies]
chrono = "^0.4.0"
indicatif = "^0.15.0"
itertools = "^0.9.0"
rand = "^0.7.3"
rayon = "^1.3.1"

[profile.release]
opt-level = 3
lto = true
debug-assertions = false
