[package]
name = "ray"
version = "0.1.0"
authors = ["Mikhail Pak <code@mp4096.com>"]
edition = "2018"


[dependencies]
indicatif = "^0.15.0"
itertools = "^0.9.0"
rand = "^0.7.3"

# [profile.release]
# opt-level = 3
# lto = true
# debug-assertions = false
